language: java
jdk:
- openjdk8

services:
- docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - GRADLE_VERSION=5.6.2
  - BITCOIND_CONNECTOR_TAG=v0.16.0
  - BITCOINJ_TAG=0.16.9-LIB
  - LATEST_VERSION=$(git log -n 1 --pretty=format:"%h")

install:
- sudo apt-get -qq update
- sudo apt-get install -y protobuf-compiler

before_script:
- gradle -version
- gradle wrapper --gradle-version=$GRADLE_VERSION
- "./scripts/install-deps.sh"

script:
- ls -l "xyz.balzaclang.balzac" | grep -e "xyz\.balzaclang\.balzac\.lib.*-bundled\.jar"
- mvn -f xyz.balzaclang.balzac.parent/ -U clean install

after_success:
- mvn -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN
- docker build -f docker/Dockerfile-slim -t balzaclang/balzac:latest -t balzaclang/balzac:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm32v7 -t balzaclang/balzac-arm32v7:latest -t balzaclang/balzac-arm32v7:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm64v8 -t balzaclang/balzac-arm64v8:latest -t balzaclang/balzac-arm64v8:${LATEST_VERSION} .

notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always

deploy:
- provider: releases
  prerelease: true
  api_key:
    secure: K4J8QK61J2pfJxEZ6h+s/2I9OCXXFkMQ8PXTSCm++1flTYYi3KCM2tG1w9wEhyktQuoNUHZL338ha7VBw++ZTysbPrCsSrI4vETiuPOeVXGrpzOtnCu+hqpnmjgW+GxFbBpZ1EGTJRMnMjIqIc1WitcVu5UX79lz/kD+v0KZBerhrbdk21yG52ejjTXQ9z7qEGfQ/6FJDeipZ+Nz5sXyfwlJhGN4kPkTM0wQLoUEOdzOCuat5vO/jdjSDfURR3WAUqa73By2Rv6Pul3EirzgAC2Pq/laGrEQFjmJjsNHX44Uh2mgLPAjTt42viDcYkvqeBBsiWoRdNaDVH5hBYlfHAP5HxDGVdUO/p8EEuJBzYxFMm0hDOFr4fcI885ur8kaJCR/0TXefaHU1h804WGvjuPZtPDWfUzB2wBXKGFDTV96PRFzNdEa38eN1jQjYjP7D3eFj2QOh8PhEEQsXtwqeTqfbdvvPJzB1auzEHQIrR4OrOo8aY/w/20FXT5mp3o/QjXsWw/+oFBb3CKRkMa/dK00yYdxgiMX4gv0orO7mGvnE/9qPFVgyv3e722AND3NMH5DZ9iagU/H/1bmwHwcmiaCflGXSuc7ZSXw6OkGm/Dyt/vyfGfP0f045Uw05yfS2OF0gFLxGE0XrlzQdk726aCvekw15uK/mU6+7d5BSaw=
  file_glob: true
  file: xyz.balzaclang.balzac.web/target/balzac*.war
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
    repo: balzac-lang/balzac
- provider: script
  script: bash scripts/docker_push.sh
  on:
    tags: true
    jdk: openjdk8
    repo: balzac-lang/balzac


